name: Compile TypeScript

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install TypeScript
        run: npm install -g typescript
      - name: Compile TypeScript
        run: tsc app.ts --outDir dist
      - name: Commit compiled files
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add dist/app.js
          git commit -m "Compile TypeScript" || echo "No changes to commit"
          git push
